apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pocs.istio.com
spec:
  group: istio.com
  names:
    kind: Canary
    plural: pocs
    singular: poc
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              sources:
                type: array
                items:
                  type: string
              conf:
                type: object
                properties:
                  split:
                    type: array
                    items:
                      type: object
                      properties:
                        weight:
                          type: number
                        destination:
                          type: object
                          properties:
                            service:
                              type: string
                            version:
                              type: string
                   
    subresources:
     status: {}
