apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: canary-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: simplify.istiocrd/v1
    resource: canarys
  childResources:
  - apiVersion: networking.istio.io/v1alpha3
    resource: virtualservices
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://istio-webhook-service.test/sync
